CREATE TABLE IF NOT EXISTS Musicas (musi_id SERIAL, musi_nome VARCHAR(45), musi_duracao VARCHAR(45), musi_compositor VARCHAR(45), CONSTRAINT pk_Musicas PRIMARY KEY (musi_id));

CREATE TABLE IF NOT EXISTS Cargos (cargo_id SERIAL, cargo_nome VARCHAR(45) NOT NULL UNIQUE, cargo_funcao VARCHAR(200) DEFAULT 'não especificado', CONSTRAINT pk_Cargos PRIMARY KEY (cargo_id));

CREATE TABLE IF NOT EXISTS Fornecedores (forne_id SERIAL, forne_nome VARCHAR(45) NOT NULL, forne_cnpj VARCHAR(18) NOT NULL UNIQUE, forne_endereco TEXT UNIQUE, CONSTRAINT pk_Fornecedor PRIMARY KEY (forne_id));

CREATE TABLE IF NOT EXISTS Formacao (forma_id SERIAL, forma_nome VARCHAR(45) NOT NULL UNIQUE, forma_jsonPalco VARCHAR NOT NULL, forma_img VARCHAR(50) NOT NULL , musi_id INT NULL, CONSTRAINT pk_Formacao PRIMARY KEY (forma_id), CONSTRAINT fk_Formacao_Musicas FOREIGN KEY (musi_id) REFERENCES Musicas (musi_id) ON DELETE CASCADE);

CREATE TABLE IF NOT EXISTS Instrumentos (instru_id SERIAL, instru_nome VARCHAR(45) NOT NULL UNIQUE, instru_img TEXT NOT NULL, forne_id INT NOT NULL, instru_ativo BOOLEAN DEFAULT TRUE, CONSTRAINT pk_Instrumentos PRIMARY KEY (instru_id), CONSTRAINT fk_Instrumentos_Fornecedores FOREIGN KEY (forne_id) REFERENCES Fornecedores(forne_id) ON DELETE CASCADE);

CREATE TABLE IF NOT EXISTS Apresentacao (aprese_id SERIAL, aprese_nome VARCHAR(45) NOT NULL UNIQUE, agen_status VARCHAR(1) DEFAULT 'N', aprese_status VARCHAR(1) DEFAULT 'I', CONSTRAINT pk_Apresentacao PRIMARY KEY (aprese_id));

CREATE TABLE IF NOT EXISTS Membros (membro_id SERIAL,membro_cpf VARCHAR(14) UNIQUE, membro_nome VARCHAR(45) NOT NULL UNIQUE, membro_dtnascimento DATE NOT NULL, membro_sexo CHAR(1) NOT NULL CHECK (membro_sexo IN ('F', 'f', 'M', 'm')) , membro_endereco TEXT NOT NULL, cargo_id INT NULL,membro_experiencia INT NOT NULL, CONSTRAINT pk_Membros PRIMARY KEY (membro_id),CONSTRAINT fk_Membros_Cargos FOREIGN KEY (cargo_id) REFERENCES Cargos(cargo_id) ON DELETE RESTRICT);

CREATE TABLE IF NOT EXISTS DocTxt (doc_id SERIAL, doc_nome VARCHAR(100) NOT NULL, doc_conteudo TEXT, aprese_id INT, CONSTRAINT pk_DocTxt PRIMARY KEY (doc_id), CONSTRAINT fk_DocTxt_Apresentacao FOREIGN KEY (aprese_id) REFERENCES Apresentacao(aprese_id) ON DELETE CASCADE);

create table if not exists estoque(est_id serial,instru_id int not null unique,est_quant int not null, constraint pk_estoque primary key (instru_id),constraint fk_estoqueInstru foreign key (instru_id) references instrumentos(instru_id));
create table if not exists movimentacao (mov_id serial, instru_id int not null, mov_data timestamptz not null, mov_tipo varchar(10) not null, mov_quant int not null, mov_valor decimal, mov_motivo varchar(1000), constraint pk_mov primary key (mov_id), constraint fk_movInstru foreign key (instru_id) references instrumentos (instru_id));
create table if not exists usuario (usu_id serial, usu_nome varchar(50) unique, usu_senha varchar(50), membro_id int unique, constraint pk_usuario primary key (usu_id), constraint fk_usuarioMembro foreign key (membro_id) references membros (membro_id) ON DELETE CASCADE);

CREATE TABLE IF NOT EXISTS Agenda (agenda_id SERIAL, agenda_local TEXT, agenda_data DATE, agenda_horario TIME, aprese_id INT, CONSTRAINT pk_Agenda PRIMARY KEY (agenda_id), CONSTRAINT fk_Agenda_Apresentacao FOREIGN KEY (aprese_id) REFERENCES Apresentacao(aprese_id) ON DELETE CASCADE);

CREATE TABLE IF NOT EXISTS ListaMusicas (musi_id INT, aprese_id INT, forma_id INT, CONSTRAINT pk_ListaMusicas PRIMARY KEY (musi_id, aprese_id, forma_id), CONSTRAINT fk_ListaMusicas_Musicas FOREIGN KEY (musi_id) REFERENCES Musicas(musi_id) ON DELETE CASCADE, CONSTRAINT fk_ListaMusicas_Apresentacao FOREIGN KEY (aprese_id) REFERENCES Apresentacao(aprese_id) ON DELETE CASCADE, CONSTRAINT fk_ListaMusicas_Formacao FOREIGN KEY (forma_id) REFERENCES Formacao(forma_id) ON DELETE CASCADE);

CREATE TABLE IF NOT EXISTS membros_formacao (id_formacao INT NOT NULL,id_membro INT NOT NULL,id_instrumento INT NULL,       indice_instrumento INT NULL,   CONSTRAINT pk_membros_formacao PRIMARY KEY (id_formacao, id_membro),CONSTRAINT fk_memform_formacao FOREIGN KEY (id_formacao) REFERENCES Formacao(forma_id) ON DELETE CASCADE,CONSTRAINT fk_memform_membro FOREIGN KEY (id_membro) REFERENCES Membros(membro_id),CONSTRAINT fk_memform_instrumento FOREIGN KEY (id_instrumento) REFERENCES Instrumentos(instru_id));

CREATE TABLE IF NOT EXISTS membros_apresentacao (aprese_id INT NOT NULL, membro_id INT NOT NULL, CONSTRAINT pk_membros_apresentacao PRIMARY KEY (aprese_id, membro_id), CONSTRAINT fk_memapre_apresentacao FOREIGN KEY (aprese_id) REFERENCES Apresentacao(aprese_id) ON DELETE CASCADE, CONSTRAINT fk_memapre_membro FOREIGN KEY (membro_id) REFERENCES Membros(membro_id) );

CREATE TABLE IF NOT EXISTS instrumentos_formacao (id_formacao INT NOT NULL,id_instrumento INT NOT NULL,quantidade INT NOT NULL CHECK (quantidade > 0),CONSTRAINT pk_instrumentos_formacao PRIMARY KEY (id_formacao, id_instrumento),CONSTRAINT fk_instform_formacao FOREIGN KEY (id_formacao) REFERENCES Formacao(forma_id) ON DELETE CASCADE,CONSTRAINT fk_instform_instrumento FOREIGN KEY (id_instrumento) REFERENCES Instrumentos(instru_id));

CREATE OR REPLACE FUNCTION fn_verifica_data_agenda() RETURNS TRIGGER AS $$ BEGIN IF NEW.agenda_data < CURRENT_DATE THEN RAISE EXCEPTION 'Dia do evento anterior ao dia de hoje' USING ERRCODE = 'P0001'; ELSIF NEW.agenda_data = CURRENT_DATE AND NEW.agenda_horario <= CURRENT_TIME THEN RAISE EXCEPTION 'Horario do evento anterior ao horario atual'; END IF; RETURN NEW; END; $$ LANGUAGE plpgsql;

CREATE TRIGGER trg_verifica_data_agenda BEFORE INSERT ON agenda FOR EACH ROW EXECUTE FUNCTION fn_verifica_data_agenda();

CREATE OR REPLACE FUNCTION fn_novo_instrumento_estoque() RETURNS TRIGGER AS $$ BEGIN INSERT INTO estoque (instru_id, est_quant) VALUES (NEW.instru_id, 0); RETURN NEW; END; $$ LANGUAGE plpgsql;

CREATE OR REPLACE TRIGGER novoInstrumentoEstoque AFTER INSERT ON Instrumentos FOR EACH ROW EXECUTE FUNCTION fn_novo_instrumento_estoque();

CREATE TABLE IF NOT EXISTS membros_formacao (id_mf SERIAL PRIMARY KEY,id_formacao INT NOT NULL,id_membro INT NOT NULL,id_instrumento INT NULL,indice_instrumento INT NULL,CONSTRAINT fk_memform_formacao FOREIGN KEY (id_formacao) REFERENCES Formacao(forma_id) ON DELETE CASCADE,CONSTRAINT fk_memform_membro FOREIGN KEY (id_membro) REFERENCES Membros(membro_id),CONSTRAINT fk_memform_instrumento FOREIGN KEY (id_instrumento) REFERENCES Instrumentos(instru_id));

CREATE OR REPLACE FUNCTION fn_atualiza_status_apresentacao() RETURNS TRIGGER AS $$ DECLARE v_aprese_id INT; v_valido BOOLEAN; BEGIN IF (TG_OP = 'DELETE') THEN IF TG_TABLE_NAME = 'listamusicas' THEN v_aprese_id := OLD.aprese_id; ELSIF TG_TABLE_NAME = 'membros_apresentacao' THEN v_aprese_id := OLD.aprese_id; ELSIF TG_TABLE_NAME = 'membros_formacao' THEN SELECT lm.aprese_id INTO v_aprese_id FROM ListaMusicas lm WHERE lm.forma_id = OLD.id_formacao LIMIT 1; END IF; ELSE IF TG_TABLE_NAME = 'listamusicas' THEN v_aprese_id := NEW.aprese_id; ELSIF TG_TABLE_NAME = 'membros_apresentacao' THEN v_aprese_id := NEW.aprese_id; ELSIF TG_TABLE_NAME = 'membros_formacao' THEN SELECT lm.aprese_id INTO v_aprese_id FROM ListaMusicas lm WHERE lm.forma_id = NEW.id_formacao LIMIT 1; END IF; END IF; IF v_aprese_id IS NULL THEN RETURN NULL; END IF; SELECT EXISTS (SELECT 1 FROM ListaMusicas lm JOIN membros_formacao mf ON mf.id_formacao = lm.forma_id JOIN membros_apresentacao ma ON ma.aprese_id = lm.aprese_id AND ma.membro_id = mf.id_membro WHERE lm.aprese_id = v_aprese_id AND mf.id_instrumento IS NOT NULL) INTO v_valido; IF v_valido THEN UPDATE Apresentacao SET aprese_status = 'C' WHERE aprese_id = v_aprese_id; ELSE UPDATE Apresentacao SET aprese_status = 'I' WHERE aprese_id = v_aprese_id; END IF; RETURN NULL; END; $$ LANGUAGE plpgsql;

CREATE TRIGGER trg_status_aprese_musicas AFTER INSERT OR UPDATE OR DELETE ON ListaMusicas FOR EACH ROW EXECUTE FUNCTION fn_atualiza_status_apresentacao();

CREATE TRIGGER trg_status_aprese_membros_ap AFTER INSERT OR UPDATE OR DELETE ON membros_apresentacao FOR EACH ROW EXECUTE FUNCTION fn_atualiza_status_apresentacao();

CREATE TRIGGER trg_status_aprese_membros_fc AFTER INSERT OR UPDATE OR DELETE ON membros_formacao FOR EACH ROW EXECUTE FUNCTION fn_atualiza_status_apresentacao();

INSERT INTO Fornecedores (forne_nome, forne_cnpj, forne_endereco) VALUES ('Taiko Imports','12.345.678/0001-10','Rua dos Tambores, 120 - São Paulo'),('Nihon Instruments','98.765.432/0001-55','Av. Japão, 450 - Curitiba'),('Kumi Daiko Supply','45.123.999/0001-77','Rua Sakura, 88 - Londrina');

INSERT INTO Cargos (cargo_nome, cargo_funcao) VALUES ('Lider','Coordena apresentações e ensaios'),('Instrutor','Treina novos integrantes'),('Percussionista','Executa instrumentos nas apresentações'),('Organizador','Cuida da logística'),('Auxiliar','Auxilia montagem e transporte');

INSERT INTO Musicas (musi_nome, musi_duracao, musi_compositor) VALUES ('Matsuri Beat','04:20','Kenji Takahashi'),('Raijin no Taiko','03:50','Hiro Tanaka'),('Kaze no Odori','05:10','Aiko Suzuki'),('Sakura Impact','04:45','Daichi Watanabe'),('Yami no Rhythm','06:00','Rin Kobayashi'),('Tsunami Pulse','03:40','Haru Yamamoto'),('Dragon Echo','05:30','Sora Fujimoto'),('Akai Rhythm','04:05','Naoki Saito');

INSERT INTO Membros (membro_cpf, membro_nome, membro_dtnascimento, membro_sexo, membro_endereco, cargo_id, membro_experiencia) VALUES ('111.111.111-01','Akira Souza','1998-01-10','M','Rua A, 10',1,8),('111.111.111-02','Bruna Tanaka','1999-02-11','F','Rua B, 11',2,6),('111.111.111-03','Carlos Saito','2000-03-12','M','Rua C, 12',3,4),('111.111.111-04','Daniela Kato','1997-04-13','F','Rua D, 13',3,7),('111.111.111-05','Eduardo Hayashi','1996-05-14','M','Rua E, 14',4,10),('111.111.111-06','Fernanda Mori','2001-06-15','F','Rua F, 15',5,2),('111.111.111-07','Gabriel Honda','1995-07-16','M','Rua G, 16',1,12),('111.111.111-08','Helena Kimura','1998-08-17','F','Rua H, 17',2,5),('111.111.111-09','Igor Fujita','2002-09-18','M','Rua I, 18',3,3),('111.111.111-10','Julia Watanabe','1994-10-19','F','Rua J, 19',4,11),('111.111.111-11','Kaio Ueda','1997-11-20','M','Rua K, 20',5,6),('111.111.111-12','Larissa Noda','1999-12-21','F','Rua L, 21',3,4),('111.111.111-13','Marcos Ito','2000-01-22','M','Rua M, 22',2,5),('111.111.111-14','Natasha Arai','1996-02-23','F','Rua N, 23',1,9),('111.111.111-15','Otavio Shimizu','1995-03-24','M','Rua O, 24',3,10),('111.111.111-16','Patricia Ono','1998-04-25','F','Rua P, 25',4,7),('111.111.111-17','Rafael Miyake','2001-05-26','M','Rua Q, 26',5,2),('111.111.111-18','Sabrina Koga','1997-06-27','F','Rua R, 27',2,6),('111.111.111-19','Tiago Endo','1999-07-28','M','Rua S, 28',3,5),('111.111.111-20','Vivian Sakai','2000-08-29','F','Rua T, 29',4,4),('111.111.111-21','Willian Ota','1996-09-30','M','Rua U, 30',1,8),('111.111.111-22','Ximena Higa','1995-10-01','F','Rua V, 31',2,9),('111.111.111-23','Yuri Aoki','1998-11-02','M','Rua W, 32',3,5),('111.111.111-24','Zelia Takeda','1997-12-03','F','Rua X, 33',5,6),('111.111.111-25','André Kinoshita','1994-01-04','M','Rua Y, 34',1,12),('111.111.111-26','Bianca Uehara','2002-02-05','F','Rua Z, 35',2,2),('111.111.111-27','Caio Nishimura','1999-03-06','M','Rua AA, 36',3,5),('111.111.111-28','Debora Yamada','1998-04-07','F','Rua AB, 37',4,6),('111.111.111-29','Enzo Hoshino','1997-05-08','M','Rua AC, 38',5,7),('111.111.111-30','Flavia Sugimoto','1996-06-09','F','Rua AD, 39',1,9),('111.111.111-31','Gustavo Inoue','2001-07-10','M','Rua AE, 40',2,3),('111.111.111-32','Heloisa Nakata','2000-08-11','F','Rua AF, 41',3,4),('111.111.111-33','Ivan Matsuda','1995-09-12','M','Rua AG, 42',4,10),('111.111.111-34','Joana Ogawa','1999-10-13','F','Rua AH, 43',5,5),('111.111.111-35','Kevin Sakamoto','1998-11-14','M','Rua AI, 44',1,7),('111.111.111-36','Lucia Hirano','1997-12-15','F','Rua AJ, 45',2,6),('111.111.111-37','Mateus Kubota','1996-01-16','M','Rua AK, 46',3,8),('111.111.111-38','Nicole Nakashima','2002-02-17','F','Rua AL, 47',4,2),('111.111.111-39','Oscar Nishida','1994-03-18','M','Rua AM, 48',5,11),('111.111.111-40','Priscila Furukawa','1995-04-19','F','Rua AN, 49',1,10);

INSERT INTO usuario (usu_nome, usu_senha, membro_id) VALUES ('akira','123',1),('bruna','123',2),('carlos','123',3),('daniela','123',4),('eduardo','123',5),('fernanda','123',6),('gabriel','123',7),('helena','123',8),('igor','123',9),('julia','123',10);
