spring.application.name=FrontEnd
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

# Permite que os provedores de nuvem (Render, Railway) decidam a porta que a aplicaçao deve usar.
# Caso não haja porta definida (ex: rodando no seu PC), ele usará a porta 8080.
server.port=${PORT:8080}
